package main

import "github.com/c-bata/go-prompt"

var ScriptCategories = []prompt.Suggest{
	{Text: "auth", Description: "Category - Tests authentication credentials and bypass mechanisms."},
	{Text: "broadcast", Description: "Category - Discovers hosts via broadcast network protocols."},
	{Text: "brute", Description: "Category - Performs brute-force password guessing attacks."},
	{Text: "default.discovery", Description: "Category - Runs default scripts for service and host discovery."},
	{Text: "dos", Description: "Category - Tests for denial-of-service vulnerabilities."},
	{Text: "exploit", Description: "Category - Attempts to exploit known vulnerabilities."},
	{Text: "external", Description: "Category - Interacts with external services or resources."},
	{Text: "fuzzer", Description: "Category - Sends malformed inputs to test service robustness."},
	{Text: "intrusive", Description: "Category - Performs aggressive scans that may disrupt services."},
	{Text: "malware", Description: "Category - Detects malware or backdoors on systems."},
	{Text: "safe", Description: "Category - Runs non-intrusive scripts unlikely to cause harm."},
	{Text: "version", Description: "Category - Identifies service versions and software details."},
	{Text: "vuln", Description: "Category - Scans for known vulnerabilities in services."},
}

var SudoRequiredFlags = []string{
	"-sS",
	"-sU",
	"-sY",
	"-sO",
	"-sW",
	"-sM",
	"-sF",
	"-sX",
	"-sN",
	"--scanflags",
	"-O",
	"-p",
	"--script",
	"--reason",
	"--spoof-source",
	"--badsum",
	"--traceroute",
	"--data",
	"--data-length",
	"--data-string",
	"--ip-options",
	"-e",
	"-S",
	"--proxies",
	"-T4",
	"-T5",
	"--min-rate",
	"--max-rate",
}

var Suggestions = []prompt.Suggest{
	{Text: "-iL <inputfilename>", Description: "Input targets from a file specified by <inputfilename>."},
	{Text: "-iR <num_hosts>", Description: "Choose <num_hosts> random targets to scan."},
	{Text: "--exclude <host1,...>", Description: "Exclude specified hosts/networks from the scan."},
	{Text: "--excludefile <exclude_file>", Description: "Exclude targets listed in the <exclude_file>."},
	{Text: "-sL", Description: "List Scan: Simply list targets without sending packets."},
	{Text: "-sn", Description: "Ping Scan: Disable port scan, only perform host discovery."},
	{Text: "-Pn", Description: "Skip host discovery; treat all targets as online."},
	{Text: "-PS<portlist>", Description: "Host discovery using TCP SYN probes to specified ports (default 80)."},
	{Text: "-PA<portlist>", Description: "Host discovery using TCP ACK probes to specified ports (default 80)."},
	{Text: "-PU<portlist>", Description: "Host discovery using UDP probes to specified ports (default 40125)."},
	{Text: "-PY<portlist>", Description: "Host discovery using SCTP INIT probes to specified ports (default 80)."},
	{Text: "-PE", Description: "Host discovery using ICMP echo request probes."},
	{Text: "-PP", Description: "Host discovery using ICMP timestamp request probes."},
	{Text: "-PM", Description: "Host discovery using ICMP netmask request probes."},
	{Text: "-PO<protocol_list>", Description: "Host discovery using IP protocol ping probes (default 1,2,4)."},
	{Text: "-n", Description: "Disable DNS resolution."},
	{Text: "-R", Description: "Enable DNS resolution for all targets."},
	{Text: "--dns-servers <servers>", Description: "Specify custom DNS servers for reverse lookups."},
	{Text: "--system-dns", Description: "Use the operating system's DNS resolver."},
	{Text: "--traceroute", Description: "Trace the network path to each host after scanning."},
	{Text: "-sS", Description: "TCP SYN (stealth) scan (default for privileged users)."},
	{Text: "-sT", Description: "TCP connect scan (default for unprivileged users)."},
	{Text: "-sA", Description: "TCP ACK scan (for mapping firewall rulesets)."},
	{Text: "-sW", Description: "TCP Window scan (may differentiate open/closed ports on some systems)."},
	{Text: "-sM", Description: "TCP Maimon scan (FIN/ACK probe)."},
	{Text: "-sU", Description: "UDP scan."},
	{Text: "-sN", Description: "TCP Null scan (flags=0)."},
	{Text: "-sF", Description: "TCP FIN scan (flags=FIN)."},
	{Text: "-sX", Description: "TCP Xmas scan (flags=FIN,PSH,URG)."},
	{Text: "--scanflags <flags>", Description: "Customize TCP scan using specified flags (URG, ACK, PSH, RST, SYN, FIN)."},
	{Text: "-sI <zombie_host[:probeport]>", Description: "Idle (zombie) scan (truly blind scan)."},
	{Text: "-sY", Description: "SCTP INIT scan."},
	{Text: "-sZ", Description: "SCTP COOKIE-ECHO scan."},
	{Text: "-sO", Description: "IP protocol scan (determine supported IP protocols)."},
	{Text: "-b <ftp_relay_host>", Description: "FTP bounce scan (rarely works)."},
	{Text: "-p <port_ranges>", Description: "Scan only specified ports (e.g., -p22, -p1-100, -p U:53,T:21-25,80)."},
	{Text: "--exclude-ports <port_ranges>", Description: "Exclude specified ports from scanning."},
	{Text: "-F", Description: "Fast scan (scan top 100 ports instead of default 1000)."},
	{Text: "-r", Description: "Scan ports sequentially (don't randomize)."},
	{Text: "--top-ports <number>", Description: "Scan the <number> most common ports."},
	{Text: "--port-ratio <ratio>", Description: "Scan ports more common than <ratio> (0.0 to 1.0)."},
	{Text: "-sV", Description: "Enable service/version detection."},
	{Text: "--version-intensity <0-9>", Description: "Set version detection intensity (0=light, 9=try all probes, default 7)."},
	{Text: "--version-light", Description: "Enable light version detection (intensity 2)."},
	{Text: "--version-all", Description: "Try all probes for version detection (intensity 9)."},
	{Text: "--version-trace", Description: "Trace version scanning activity (for debugging)."},
	{Text: "-sC", Description: "Perform script scan using the default set of scripts (--script=default)."},
	{Text: "--script <scripts>", Description: "Run specified NSE scripts (files, categories, directories, expressions)."},
	{Text: "--script-args <args>", Description: "Provide comma-separated arguments (n1=v1,...) to NSE scripts."},
	{Text: "--script-args-file <filename>", Description: "Provide NSE script arguments from a file."},
	{Text: "--script-trace", Description: "Trace NSE script activity (data sent/received)."},
	{Text: "--script-updatedb", Description: "Update the NSE script database (run alone)."},
	{Text: "--script-help <scripts>", Description: "Show help for specified NSE scripts (run alone or with targets)."},
	{Text: "-O", Description: "Enable operating system detection."},
	{Text: "--osscan-limit", Description: "Limit OS detection to promising targets (at least one open and one closed TCP port found)."},
	{Text: "--osscan-guess", Description: "Guess operating system more aggressively (equivalent to --fuzzy)."},
	{Text: "-T<0-5>", Description: "Set timing template (0=paranoid, 1=sneaky, 2=polite, 3=normal, 4=aggressive, 5=insane)."},
	{Text: "--min-hostgroup <size>", Description: "Set minimum parallel host scan group size."},
	{Text: "--max-hostgroup <size>", Description: "Set maximum parallel host scan group size."},
	{Text: "--min-parallelism <numprobes>", Description: "Set minimum number of outstanding probes for a group."},
	{Text: "--max-parallelism <numprobes>", Description: "Set maximum number of outstanding probes for a group."},
	{Text: "--min-rtt-timeout <time>", Description: "Set minimum probe round trip time timeout."},
	{Text: "--max-rtt-timeout <time>", Description: "Set maximum probe round trip time timeout."},
	{Text: "--initial-rtt-timeout <time>", Description: "Set initial probe round trip time timeout."},
	{Text: "--max-retries <tries>", Description: "Set maximum number of port scan probe retransmissions."},
	{Text: "--host-timeout <time>", Description: "Give up on slow target hosts after this much time (e.g., 30m, 900s)."},
	{Text: "--script-timeout <time>", Description: "Set maximum execution time for individual NSE script instances."},
	{Text: "--scan-delay <time>", Description: "Wait at least <time> between probes sent to a host."},
	{Text: "--max-scan-delay <time>", Description: "Set maximum delay Nmap will allow between probes."},
	{Text: "--min-rate <number>", Description: "Send packets no slower than <number> per second."},
	{Text: "--max-rate <number>", Description: "Send packets no faster than <number> per second."},
	{Text: "--defeat-rst-ratelimit", Description: "Ignore RST packet rate limits (speeds up scans, may misclassify closed ports as filtered)."},
	{Text: "--defeat-icmp-ratelimit", Description: "Ignore ICMP error message rate limits for UDP scans (speeds up scans, may misclassify ports)."},
	{Text: "-f", Description: "Fragment IP packets (using 8-byte fragments). Use -ff for 16-byte fragments."},
	{Text: "--mtu <value>", Description: "Fragment IP packets using a specific MTU (must be multiple of 8)."},
	{Text: "-D <decoy1,decoy2[,ME],...>", Description: "Cloak scan with decoys (use ME for your real IP, RND for random)."},
	{Text: "-S <IP_Address>", Description: "Spoof source IP address."},
	{Text: "-e <interface>", Description: "Use specified network interface."},
	{Text: "-g <portnum>", Description: "Use specified source port number (same as --source-port)."},
	{Text: "--source-port <portnum>", Description: "Use specified source port number (same as -g)."},
	{Text: "--proxies <url1,[url2],...>", Description: "Relay TCP connections through HTTP/SOCKS4 proxies."},
	{Text: "--data <hex_string>", Description: "Append custom binary payload (hex) to packets."},
	{Text: "--data-string <string>", Description: "Append custom string payload to packets."},
	{Text: "--data-length <number>", Description: "Append random data payload of specified length to packets."},
	{Text: "--ip-options <options>", Description: "Send packets with specified IP options (e.g., R, S route, L route, hex)."},
	{Text: "--ttl <value>", Description: "Set IPv4 time-to-live field."},
	{Text: "--randomize-hosts", Description: "Randomize order of target hosts."},
	{Text: "--spoof-mac <mac/prefix/vendor/0>", Description: "Spoof source MAC address (implies --send-eth)."},
	{Text: "--badsum", Description: "Send packets with bogus TCP/UDP/SCTP checksums."},
	{Text: "--adler32", Description: "Use deprecated Adler32 checksum for SCTP (for legacy systems)."},
	{Text: "-oN <file>", Description: "Output scan in normal format to <file>."},
	{Text: "-oX <file>", Description: "Output scan in XML format to <file>."},
	{Text: "-oS <file>", Description: "Output scan in sCRiPt KiDDi3 format to <file>."},
	{Text: "-oG <file>", Description: "Output scan in Grepable format to <file>."},
	{Text: "-oA <basename>", Description: "Output in Normal, XML, and Grepable formats using <basename> prefix."},
	{Text: "-v", Description: "Increase verbosity level (use -vv or more for greater effect)."},
	{Text: "-d", Description: "Increase debugging level (use -dd or more for greater effect)."},
	{Text: "--reason", Description: "Display the reason for port states and host status."},
	{Text: "--stats-every <time>", Description: "Print periodic timing stats every <time> (e.g., 10s, 1m)."},
	{Text: "--packet-trace", Description: "Trace all packets sent and received."},
	{Text: "--open", Description: "Show only open, open|filtered, or unfiltered ports."},
	{Text: "--iflist", Description: "List interfaces and routes detected by Nmap and exit."},
	{Text: "--append-output", Description: "Append results to output files instead of overwriting."},
	{Text: "--resume <filename>", Description: "Resume an aborted scan from an output file (.nmap, .gnmap, .xml)."},
	{Text: "--noninteractive", Description: "Disable runtime keyboard interactions."},
	{Text: "--stylesheet <path_or_URL>", Description: "Set XSL stylesheet for XML output (e.g., for HTML conversion)."},
	{Text: "--webxml", Description: "Use nmap.org's stylesheet for portable XML-to-HTML rendering."},
	{Text: "--no-stylesheet", Description: "Omit XSL stylesheet declaration from XML output."},
	{Text: "-6", Description: "Enable IPv6 scanning."},
	{Text: "-A", Description: "Enable Aggressive scan options: OS detection (-O), version detection (-sV), script scanning (-sC), traceroute (--traceroute)."},
	{Text: "--datadir <directory>", Description: "Specify custom Nmap data file directory (run alone or with targets)."},
	{Text: "--send-eth", Description: "Send using raw Ethernet frames (Layer 2)."},
	{Text: "--send-ip", Description: "Send using raw IP packets (Layer 3)."},
	{Text: "--privileged", Description: "Assume user has privileges for raw sockets/sniffing."},
	{Text: "--unprivileged", Description: "Assume user lacks privileges for raw sockets/sniffing."},
	{Text: "-V", Description: "Print Nmap version number and exit."},
	{Text: "-h", Description: "Print help summary page and exit."},
	{Text: "--resolve-all", Description: "Scan all IP addresses a hostname resolves to."},
	{Text: "--unique", Description: "Scan each IP address only once, even if specified multiple times."},
	{Text: "--disable-arp-ping", Description: "Disable ARP/ND host discovery on local network."},
	{Text: "--discovery-ignore-rst", Description: "Ignore RST packets during host discovery (useful vs some firewalls)."},
	{Text: "--allports", Description: "Don't exclude any ports (like TCP 9100) from version detection."},
	{Text: "--max-os-tries <number>", Description: "Set max number of OS detection attempts per host."},
}
