package main

import "github.com/c-bata/go-prompt"

var Suggestions = []prompt.Suggest{
	{Text: "nmap -sC -sV -oA top-1000-ports ip_or_host1,ip_or_host2,...", Description: "Perform service/version detection (-sV), default script scanning (-sC) of the top 1000 ports, writing results (-oA) to Normal, XML, and Grepable files."},
	{Text: "nmap --script 'default and safe' ip_or_host1,ip_or_host2,...", Description: "Scan target(s) using only NSE scripts that are in both the 'default' AND 'safe' categories."},
	{Text: "nmap -iL <inputfilename>", Description: "Input targets from a file specified by <inputfilename>."},
	{Text: "nmap -iR <num_hosts>", Description: "Choose <num_hosts> random targets to scan."},
	{Text: "nmap --exclude <host1,...>", Description: "Exclude specified hosts/networks from the scan."},
	{Text: "nmap --excludefile <exclude_file>", Description: "Exclude targets listed in the <exclude_file>."},
	{Text: "nmap -sL <target>", Description: "List Scan: Simply list targets without sending packets."},
	{Text: "nmap -sn <target>", Description: "Ping Scan: Disable port scan, only perform host discovery."},
	{Text: "nmap -Pn <target>", Description: "Skip host discovery; treat all targets as online."},
	{Text: "nmap -PS<portlist> <target>", Description: "Host discovery using TCP SYN probes to specified ports (default 80)."},
	{Text: "nmap -PA<portlist> <target>", Description: "Host discovery using TCP ACK probes to specified ports (default 80)."},
	{Text: "nmap -PU<portlist> <target>", Description: "Host discovery using UDP probes to specified ports (default 40125)."},
	{Text: "nmap -PY<portlist> <target>", Description: "Host discovery using SCTP INIT probes to specified ports (default 80)."},
	{Text: "nmap -PE <target>", Description: "Host discovery using ICMP echo request probes."},
	{Text: "nmap -PP <target>", Description: "Host discovery using ICMP timestamp request probes."},
	{Text: "nmap -PM <target>", Description: "Host discovery using ICMP netmask request probes."},
	{Text: "nmap -PO<protocol_list> <target>", Description: "Host discovery using IP protocol ping probes (default 1,2,4)."},
	{Text: "nmap -n <target>", Description: "Disable DNS resolution."},
	{Text: "nmap -R <target>", Description: "Enable DNS resolution for all targets."},
	{Text: "nmap --dns-servers <servers> <target>", Description: "Specify custom DNS servers for reverse lookups."},
	{Text: "nmap --system-dns <target>", Description: "Use the operating system's DNS resolver."},
	{Text: "nmap --traceroute <target>", Description: "Trace the network path to each host after scanning."},
	{Text: "nmap -sS <target>", Description: "TCP SYN (stealth) scan (default for privileged users)."},
	{Text: "nmap -sT <target>", Description: "TCP connect scan (default for unprivileged users)."},
	{Text: "nmap -sA <target>", Description: "TCP ACK scan (for mapping firewall rulesets)."},
	{Text: "nmap -sW <target>", Description: "TCP Window scan (may differentiate open/closed ports on some systems)."},
	{Text: "nmap -sM <target>", Description: "TCP Maimon scan (FIN/ACK probe)."},
	{Text: "nmap -sU <target>", Description: "UDP scan."},
	{Text: "nmap -sN <target>", Description: "TCP Null scan (flags=0)."},
	{Text: "nmap -sF <target>", Description: "TCP FIN scan (flags=FIN)."},
	{Text: "nmap -sX <target>", Description: "TCP Xmas scan (flags=FIN,PSH,URG)."},
	{Text: "nmap --scanflags <flags> <target>", Description: "Customize TCP scan using specified flags (URG, ACK, PSH, RST, SYN, FIN)."},
	{Text: "nmap -sI <zombie_host[:probeport]> <target>", Description: "Idle (zombie) scan (truly blind scan)."},
	{Text: "nmap -sY <target>", Description: "SCTP INIT scan."},
	{Text: "nmap -sZ <target>", Description: "SCTP COOKIE-ECHO scan."},
	{Text: "nmap -sO <target>", Description: "IP protocol scan (determine supported IP protocols)."},
	{Text: "nmap -b <ftp_relay_host> <target>", Description: "FTP bounce scan (rarely works)."},
	{Text: "nmap -p <port_ranges> <target>", Description: "Scan only specified ports (e.g., -p22, -p1-100, -p U:53,T:21-25,80)."},
	{Text: "nmap --exclude-ports <port_ranges> <target>", Description: "Exclude specified ports from scanning."},
	{Text: "nmap -F <target>", Description: "Fast scan (scan top 100 ports instead of default 1000)."},
	{Text: "nmap -r <target>", Description: "Scan ports sequentially (don't randomize)."},
	{Text: "nmap --top-ports <number> <target>", Description: "Scan the <number> most common ports."},
	{Text: "nmap --port-ratio <ratio> <target>", Description: "Scan ports more common than <ratio> (0.0 to 1.0)."},
	{Text: "nmap -sV <target>", Description: "Enable service/version detection."},
	{Text: "nmap --version-intensity <0-9> <target>", Description: "Set version detection intensity (0=light, 9=try all probes, default 7)."},
	{Text: "nmap --version-light <target>", Description: "Enable light version detection (intensity 2)."},
	{Text: "nmap --version-all <target>", Description: "Try all probes for version detection (intensity 9)."},
	{Text: "nmap --version-trace <target>", Description: "Trace version scanning activity (for debugging)."},
	{Text: "nmap -sC <target>", Description: "Perform script scan using the default set of scripts (--script=default)."},
	{Text: "nmap --script <scripts> <target>", Description: "Run specified NSE scripts (files, categories, directories, expressions)."},
	{Text: "nmap --script-args <args> <target>", Description: "Provide comma-separated arguments (n1=v1,...) to NSE scripts."},
	{Text: "nmap --script-args-file <filename> <target>", Description: "Provide NSE script arguments from a file."},
	{Text: "nmap --script-trace <target>", Description: "Trace NSE script activity (data sent/received)."},
	{Text: "nmap --script-updatedb", Description: "Update the NSE script database (run alone)."},
	{Text: "nmap --script-help <scripts>", Description: "Show help for specified NSE scripts (run alone or with targets)."},
	{Text: "nmap -O <target>", Description: "Enable operating system detection."},
	{Text: "nmap --osscan-limit <target>", Description: "Limit OS detection to promising targets (at least one open and one closed TCP port found)."},
	{Text: "nmap --osscan-guess <target>", Description: "Guess operating system more aggressively (equivalent to --fuzzy)."},
	{Text: "nmap -T<0-5> <target>", Description: "Set timing template (0=paranoid, 1=sneaky, 2=polite, 3=normal, 4=aggressive, 5=insane)."},
	{Text: "nmap --min-hostgroup <size> <target>", Description: "Set minimum parallel host scan group size."},
	{Text: "nmap --max-hostgroup <size> <target>", Description: "Set maximum parallel host scan group size."},
	{Text: "nmap --min-parallelism <numprobes> <target>", Description: "Set minimum number of outstanding probes for a group."},
	{Text: "nmap --max-parallelism <numprobes> <target>", Description: "Set maximum number of outstanding probes for a group."},
	{Text: "nmap --min-rtt-timeout <time> <target>", Description: "Set minimum probe round trip time timeout."},
	{Text: "nmap --max-rtt-timeout <time> <target>", Description: "Set maximum probe round trip time timeout."},
	{Text: "nmap --initial-rtt-timeout <time> <target>", Description: "Set initial probe round trip time timeout."},
	{Text: "nmap --max-retries <tries> <target>", Description: "Set maximum number of port scan probe retransmissions."},
	{Text: "nmap --host-timeout <time> <target>", Description: "Give up on slow target hosts after this much time (e.g., 30m, 900s)."},
	{Text: "nmap --script-timeout <time> <target>", Description: "Set maximum execution time for individual NSE script instances."},
	{Text: "nmap --scan-delay <time> <target>", Description: "Wait at least <time> between probes sent to a host."},
	{Text: "nmap --max-scan-delay <time> <target>", Description: "Set maximum delay Nmap will allow between probes."},
	{Text: "nmap --min-rate <number> <target>", Description: "Send packets no slower than <number> per second."},
	{Text: "nmap --max-rate <number> <target>", Description: "Send packets no faster than <number> per second."},
	{Text: "nmap --defeat-rst-ratelimit <target>", Description: "Ignore RST packet rate limits (speeds up scans, may misclassify closed ports as filtered)."},
	{Text: "nmap --defeat-icmp-ratelimit <target>", Description: "Ignore ICMP error message rate limits for UDP scans (speeds up scans, may misclassify ports)."},
	{Text: "nmap -f <target>", Description: "Fragment IP packets (using 8-byte fragments). Use -ff for 16-byte fragments."},
	{Text: "nmap --mtu <value> <target>", Description: "Fragment IP packets using a specific MTU (must be multiple of 8)."},
	{Text: "nmap -D <decoy1,decoy2[,ME],...> <target>", Description: "Cloak scan with decoys (use ME for your real IP, RND for random)."},
	{Text: "nmap -S <IP_Address> <target>", Description: "Spoof source IP address."},
	{Text: "nmap -e <interface> <target>", Description: "Use specified network interface."},
	{Text: "nmap -g <portnum> <target>", Description: "Use specified source port number (same as --source-port)."},
	{Text: "nmap --source-port <portnum> <target>", Description: "Use specified source port number (same as -g)."},
	{Text: "nmap --proxies <url1,[url2],...> <target>", Description: "Relay TCP connections through HTTP/SOCKS4 proxies."},
	{Text: "nmap --data <hex_string> <target>", Description: "Append custom binary payload (hex) to packets."},
	{Text: "nmap --data-string <string> <target>", Description: "Append custom string payload to packets."},
	{Text: "nmap --data-length <number> <target>", Description: "Append random data payload of specified length to packets."},
	{Text: "nmap --ip-options <options> <target>", Description: "Send packets with specified IP options (e.g., R, S route, L route, hex)."},
	{Text: "nmap --ttl <value> <target>", Description: "Set IPv4 time-to-live field."},
	{Text: "nmap --randomize-hosts <target>", Description: "Randomize order of target hosts."},
	{Text: "nmap --spoof-mac <mac/prefix/vendor/0> <target>", Description: "Spoof source MAC address (implies --send-eth)."},
	{Text: "nmap --badsum <target>", Description: "Send packets with bogus TCP/UDP/SCTP checksums."},
	{Text: "nmap --adler32 <target>", Description: "Use deprecated Adler32 checksum for SCTP (for legacy systems)."},
	{Text: "nmap -oN <file> <target>", Description: "Output scan in normal format to <file>."},
	{Text: "nmap -oX <file> <target>", Description: "Output scan in XML format to <file>."},
	{Text: "nmap -oS <file> <target>", Description: "Output scan in sCRiPt KiDDi3 format to <file>."},
	{Text: "nmap -oG <file> <target>", Description: "Output scan in Grepable format to <file>."},
	{Text: "nmap -oA <basename> <target>", Description: "Output in Normal, XML, and Grepable formats using <basename> prefix."},
	{Text: "nmap -v <target>", Description: "Increase verbosity level (use -vv or more for greater effect)."},
	{Text: "nmap -d <target>", Description: "Increase debugging level (use -dd or more for greater effect)."},
	{Text: "nmap --reason <target>", Description: "Display the reason for port states and host status."},
	{Text: "nmap --stats-every <time> <target>", Description: "Print periodic timing stats every <time> (e.g., 10s, 1m)."},
	{Text: "nmap --packet-trace <target>", Description: "Trace all packets sent and received."},
	{Text: "nmap --open <target>", Description: "Show only open, open|filtered, or unfiltered ports."},
	{Text: "nmap --iflist", Description: "List interfaces and routes detected by Nmap and exit."},
	{Text: "nmap --append-output <target>", Description: "Append results to output files instead of overwriting."},
	{Text: "nmap --resume <filename>", Description: "Resume an aborted scan from an output file (.nmap, .gnmap, .xml)."},
	{Text: "nmap --noninteractive <target>", Description: "Disable runtime keyboard interactions."},
	{Text: "nmap --stylesheet <path_or_URL> <target>", Description: "Set XSL stylesheet for XML output (e.g., for HTML conversion)."},
	{Text: "nmap --webxml <target>", Description: "Use nmap.org's stylesheet for portable XML-to-HTML rendering."},
	{Text: "nmap --no-stylesheet <target>", Description: "Omit XSL stylesheet declaration from XML output."},
	{Text: "nmap -6 <target>", Description: "Enable IPv6 scanning."},
	{Text: "nmap -A <target>", Description: "Enable Aggressive scan options: OS detection (-O), version detection (-sV), script scanning (-sC), traceroute (--traceroute)."},
	{Text: "nmap --datadir <directory>", Description: "Specify custom Nmap data file directory (run alone or with targets)."},
	{Text: "nmap --send-eth <target>", Description: "Send using raw Ethernet frames (Layer 2)."},
	{Text: "nmap --send-ip <target>", Description: "Send using raw IP packets (Layer 3)."},
	{Text: "nmap --privileged <target>", Description: "Assume user has privileges for raw sockets/sniffing."},
	{Text: "nmap --unprivileged <target>", Description: "Assume user lacks privileges for raw sockets/sniffing."},
	{Text: "nmap -V", Description: "Print Nmap version number and exit."},
	{Text: "nmap -h", Description: "Print help summary page and exit."},
	{Text: "nmap --resolve-all <target>", Description: "Scan all IP addresses a hostname resolves to."},
	{Text: "nmap --unique <target>", Description: "Scan each IP address only once, even if specified multiple times."},
	{Text: "nmap --disable-arp-ping <target>", Description: "Disable ARP/ND host discovery on local network."},
	{Text: "nmap --discovery-ignore-rst <target>", Description: "Ignore RST packets during host discovery (useful vs some firewalls)."},
	{Text: "nmap --allports <target>", Description: "Don't exclude any ports (like TCP 9100) from version detection."},
	{Text: "nmap --max-os-tries <number> <target>", Description: "Set max number of OS detection attempts per host."},
}

